### ISSUE TITLE
cygnus recipe is misleading w.r.t. mysql

### ISSUE THREAD

**Issue by chicco785** [smartsdk/smartsdk-recipes#15]
mysql is not in ha since it is not synched, the difference instances will end up containing different data.
i would explain this and i would not show 3 replica in the example.

**Comment by taliaga** [comment]
Good catch, probably a leftover from the first test using mongo-based example. Would you like to keep the example with mysql (fixing of course the replica number in the example) or shall leave the example with mongo replicaset? I felt like mysql to have something different in there.
Note there's a note in the readme explaining that it's up to the user to ensure the high-availability of the backend and that is technology-dependent.

**Comment by chicco785** [comment]
i would leave it in, but I would be very clear about that.
