### ISSUE TITLE
can we use a better name than test-channel?

### ISSUE THREAD

**Issue by chicco785** [smartsdk/smartsdk-recipes#16]
https://github.com/smartsdk/smartsdk-recipes/blob/c4c7f956c16f73c8d15d4868ae7c4a6cffe02fee/recipes/data-management/cygnus/ha/conf/cygnus_agent.conf#L2

**Comment by taliaga** [comment]
How about `main-channel`?

**Comment by chicco785** [comment]
question is what's the usage of that channel? if has not specific usage, main or primary is perfect

**Comment by taliaga** [comment]
well, we need at least one channel to connect sources to sinks don't we?
