### ISSUE TITLE
if it's commented should not stay in there?

### ISSUE THREAD

**Issue by chicco785** [smartsdk/smartsdk-recipes#17]
https://github.com/smartsdk/smartsdk-recipes/blob/c4c7f956c16f73c8d15d4868ae7c4a6cffe02fee/recipes/data-management/cygnus/ha/conf/cygnus_agent.conf#L20

**Comment by taliaga** [comment]
It's for convenience particularly because this is an example for new people getting acquainted with Cygnus. To me it's more useful there than not at all, but if you prefer we can remove.

**Comment by chicco785** [comment]
then it should be documented # remove the # to....
