### ISSUE TITLE
missing documentation on external networks creation

### ISSUE THREAD

**Issue by chicco785** [smartsdk/smartsdk-recipes#18]
for example, looking at the context-broker HA documentation, there is no explanation about the fact that you need to set-up two networks upfront.

**Comment by taliaga** [comment]
it is mentioned both in the home and in the [installation section](https://smartsdk.github.io/smartsdk-recipes/installation/).

**Comment by chicco785** [comment]
yes, but either you attach a reference to that, or then if you provide steps by steps instructions, not covering that, people will face errors.

check here: https://github.com/smartsdk/smartsdk-recipes/tree/master/recipes/data-management/context-broker/ha
